const ActionType = {
  MACHINE_OFFLINE: 'MACHINE_OFFLINE',
  MACHINE_ONLINE: 'MACHINE_ONLINE',
  CONTROLLER_ACCEPTED: 'CONTROLLER_ACCEPTED',
  CONTROLLER_REJECTED: 'CONTROLLER_REJECTED',
};

export default ActionType;
