const ActionType = {
  MACHINE_OFFLINE: 'MACHINE_OFFLINE',
  MACHINE_ONLINE: 'MACHINE_ONLINE',
  CONTROLLER_ACCEPTED: 'CONTROLLER_ACCEPTED',
  CONTROLLER_REJECTED: 'CONTROLLER_REJECTED',
  MACHINE_START: 'MACHINE_START',
  MACHINE_STARTED: 'MACHINE_STARTED',
  MACHINE_STOP: 'MACHINE_STOP',
  MACHINE_STOPPED: 'MACHINE_STOPPED',
};

export default ActionType;
